kind: Template
apiVersion: v1
labels:
  app: "${NAME}"
  template: "${NAME}-deployment"
  tier: backend
metadata:
  name: "${NAME}-deployment-template"
  creationTimestamp: null
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${NAME}"
      annotations:
        description: Exposes and load balances the application pods.
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        name: "${NAME}"
      type: ClusterIP
      sessionAffinity: None
  - kind: Route
    apiVersion: v1
    metadata:
      name: "${NAME}"
    spec:
      host: "${APPLICATION_DOMAIN}"
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: "${NAME}"
        weight: 100
      port:
        targetPort: 8080-tcp
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      annotations:
        description: "Defines how to deploy ${NAME}"
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: ImageStreamTag
              namespace: "${IMAGE_NAMESPACE}"
              name: "${SOURCE_IMAGE_NAME}:${TAG_NAME}"
      replicas: 1
      selector:
        name: "${NAME}"
      template:
        metadata:
          name: "${NAME}"
          labels:
            name: "${NAME}"
        spec:
          containers:
            - name: "${NAME}"
              image: ""
              ports:
                - containerPort: 8080
                  protocol: TCP
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: "${ASPNETCORE_ENVIRONMENT}"
              resources:
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
              readinessProbe:
                httpGet:
                  path: /hc
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /hc
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the resources defined in this template.
    required: true
    value: DemoJenkinsDockerCore
  - name: APPLICATION_DOMAIN
    displayName: Application Hostname
    description: >-
      The exposed hostname that will route to the application, if left blank a
      value will be defaulted.
    value: ""
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    description: >-
      The namespace of the OpenShift project containing the imagestream for the
      application.
    required: true
    value: DemoJenkinsDockerCore-tools
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: DemoJenkinsDockerCore
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: dev
  - name: ASPNETCORE_ENVIRONMENT
    displayName: AspNetCore Environment
    description: >-
      The ASP Net Core deployment environment setting, e.g., Development,
      Staging, Production
    required: true
    value: Development
  - name: TZ
    displayName: Timezone
    description: The server timezone
    required: true
    value: America/Vancouver
  - name: DemoJenkinsDockerCoreDbContext
    displayName: DemoJenkinsDockerCoreDbContext
    description: The database connection string
    required: false
    value: ''
  - name: CPU_LIMIT
    displayName: CPU Limit
    description: Maximum amount of CPU the container can use.
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Maximum amount of memory the container can use.
    value: 4Gi
  - name: CPU_REQUEST
    displayName: CPU Request
    description: Starting amount of CPU the container can use.
    value: 100m
  - name: MEMORY_REQUEST
    displayName: Memory Request
    description: Starting amount of memory the container can use.
    value: 2Gi