kind: Template
apiVersion: v1
labels:
  app: "${NAME}"
  tier: backend
metadata:
  name: "${NAME}-build-template"
  creationTimestamp: null
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
    spec:
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: "${SOURCE_IMAGE_KIND}"
            name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
          env:
            - name: DOTNET_STARTUP_PROJECT
              value: "${DOTNET_STARTUP_PROJECT}"
            - name: DOTNET_TEST_PROJECTS
              value: "${DOTNET_TEST_PROJECTS}"
            - name: DOTNET_RM_SRC
              value: "${DOTNET_RM_SRC}"
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:latest"
      resources:
        requests:
          cpu: "${CPU_REQUEST}"
          memory: "${MEMORY_REQUEST}"
        limits:
          cpu: "${CPU_LIMIT}"
          memory: "${MEMORY_LIMIT}"
parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the resources defined in this template.
    required: true
    value: demojenkinsdockercore
  - name: GIT_REPO_URL
    displayName: Git Repository URL
    description: The URL of the repository with your application source code.
    required: true
    value: "https://github.com/parulmishra/DemoJenkinsDockerCore.git"
  - name: GIT_REF
    displayName: Git Reference
    description: >-
      Set this to a branch name, tag or other ref of your repository if you are
      not using the default branch.
    required: true
    value: master
  - name: SOURCE_CONTEXT_DIR
    displayName: Context Directory
    description: >-
      Set this to the relative path to your project if it is not in the root of
      your repository.
    required: false
    value: ""
  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    description: >-
      The 'kind' (type) of the source image; typically ImageStreamTag, or
      DockerImage.
    required: true
    value: DockerImage
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the source image.
    required: true
    value: registry.access.redhat.com/dotnet/dotnet-22-rhel7
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    description: The tag of the source image.
    required: true
    value: 2.2-2
  - name: DOTNET_STARTUP_PROJECT
    displayName: DotNet Startup Project
    description: The path to the startup project for the .Net application.
    required: true
    value: DemoJenkinsDockerCore
  - name: DOTNET_TEST_PROJECTS
    displayName: DotNet Test Project(s)
    description: >-
      Used to specify the list of test projects to run. This must be project
      files or folders containing a single project file. dotnet test is invoked
      for each item.
    required: true
    value: |-
      DemoJenkinsDockerCore.Tests
  - name: DOTNET_RM_SRC
    displayName: Remove DotNet source code
    description:
      When set to true, the source code will not be included in the final image.
    required: true
    value: "true"
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: "1"
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 6Gi
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: "1"
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 4Gi
